### PR TITLE
Testing jenkins ci integration

### PR DESCRIPTION
**Pull request by paigerube14**
### Description
While setting up the jenkins integration I noticed the tests weren't actually getting the proper return code.  I fixed that as well as a lot of other small issues to get the test running. 

In the latest run you can see that it took 8 minutes: I opened issue in kraken https://github.com/cloud-bulldozer/kraken/issues/177; once that's fixed the time should be a lot less

### CODE REVIEW

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by chaitanyaenr** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by chaitanyaenr** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by paigerube14** [comment]
rerun

**Comment by chaitanyaenr** [comment]
rerun

**Comment by paigerube14** [comment]
Took out the original testing comments and doc changes. Is this ok to merge?

**Comment by chaitanyaenr** [comment]
> Took out the original testing comments and doc changes. Is this ok to merge?

Yup!

**Pull request merged**
